# -*- coding: utf-8 -*-
"""06_Correlation Heatmap

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_2oNP2mVD6NIHZxMjDLZQ7rl0qKPdT_
"""

# Index(['City', 'Temples', 'Vegetarian Restaurants', 'Marriage Rate', 'Area of Land', 'Temple Density (km^2)','Vegetarian Restaurant Density (km^2)'],dtype='object')
# Import necessary libraries
from sklearn.preprocessing import StandardScaler
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load your cleaned dataset
df = pd.read_excel('data.xlsx', header=0)

# Rename columns for clarity
df = df.rename(columns={
    'Temple Density (km^2)': 'Temple Density',
    'Vegetarian Restaurant Density (km^2)': 'Veg. Rest. Density',
    'Marriage Rate': 'Marriage Rate'
})
# print(df.columns)

# Select the columns to analyze
features = ['Marriage Rate', 'Veg. Rest. Density', 'Temple Density'] # Use the new column names here

# Calculate correlation coefficient
corr = df[features].corr()

# Draw a heat map
plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.show()