# -*- coding: utf-8 -*-
"""07_Marriage Rate by Region-box chart

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_2oNP2mVD6NIHZxMjDLZQ7rl0qKPdT_
"""

# Import necessary libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import pearsonr

# Load the dataset from Excel file
df = pd.read_excel('data.xlsx')

# Define a mapping of cities to regions
region_map = {
    'New Taipei': 'North', 'Taipei': 'North', 'Keelung': 'North',
    'Taoyuan': 'North', 'Hsinchu Ct': 'North', 'Hsinchu Co': 'North', 'Yilan': 'North',

    'Taichung': 'Central', 'Miaoli': 'Central', 'Changhua': 'Central',
    'Nantou': 'Central', 'Yunlin': 'Central',

    'Tainan': 'South', 'Kaohsiung': 'South', 'Chiayi Ct': 'South',
    'Chiayi Co': 'South', 'Pingtung': 'South',

    'Hualien': 'East', 'Taitung': 'East',

    'Penghu': 'Islands', 'Kinmen': 'Islands', 'Matsu': 'Islands'
}

# Apply region mapping to create a new 'Region' column
df["Region"] = df["City"].map(region_map)

# Create a boxplot to visualize Marriage Rate distribution by Region
plt.figure(figsize=(8, 6))
sns.boxplot(x='Region', y='Marriage Rate', data=df, hue='Region', palette='Pastel1')

# Add title and axis labels
plt.title('Marriage Rate by Region')
plt.xlabel('Region')
plt.ylabel('Marriage Rate')
plt.grid(True)

# Display the plot
plt.tight_layout()
plt.show()