# -*- coding: utf-8 -*-
"""01_Temple Density (km^2) and Vegetarian Restaurant Density (km^2) line chart

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_2oNP2mVD6NIHZxMjDLZQ7rl0qKPdT_
"""

# Index(['City', 'Temples', 'Vegetarian Restaurants', 'Marriage Rate', 'Area of Land', 'Temple Density (km^2)','Vegetarian Restaurant Density (km^2)'],dtype='object')

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import seaborn as sns
from scipy.stats import pearsonr

# Load your cleaned dataset
df = pd.read_excel('data.xlsx', header=0)

# Display the first 20 rows of the DataFrame to preview the data.
# print("df_head",df.head(20))

# Show the list of column names in the DataFrame.
# Useful for checking the exact spelling and structure of the dataset's columns.
# print("df_index",df.columns)

# Sort counties and cities by number of temples
# df_sorted = df.sort_values(by="Temples", ascending=False)

# Calculate the Pearson correlation coefficient and p-value between Kiss Count and Age of First Kiss
r_value, p_value = pearsonr(df['Vegetarian Restaurant Density (km^2)'], df['Temple Density (km^2)'])

# Create horizontal line plot
plt.figure(figsize=(12, 6))
plt.plot(df["City"], df["Temple Density (km^2)"], marker='o', label="Temples")
plt.plot(df["City"], df["Vegetarian Restaurant Density (km^2)"], marker='s', label="Vegetarian Restaurants")

# Optimize layout
plt.xticks(rotation=45, ha='right')
plt.xlabel("City")
plt.ylabel("Density")
plt.title(f"Temples and Vegetarian Restaurants by City\nr = {r_value:.2f}, p = {p_value:.3f}")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()