# -*- coding: utf-8 -*-
"""05_Vegetarian Restaurant Density (km^2) and Marriage Rate scatter chart

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_2oNP2mVD6NIHZxMjDLZQ7rl0qKPdT_
"""

# Index(['City', 'Temples', 'Vegetarian Restaurants', 'Marriage Rate', 'Area of Land', 'Temple Density (km^2)','Vegetarian Restaurant Density (km^2)'],dtype='object')
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Load your cleaned dataset
df = pd.read_excel('data(clean).xlsx', header=0)

# Calculate the Pearson correlation coefficient and p-value between Kiss Count and Age of First Kiss
r_value, p_value = pearsonr(df['Vegetarian Restaurant Density (km^2)'], df['Marriage Rate'])

# Create a scatter plot with a linear regression line
sns.lmplot(
    x='Vegetarian Restaurant Density (km^2)',                      # X-axis: total number of people kissed
    y='Marriage Rate',               # Y-axis: age when the participant had their first kiss
    data=df,
    scatter_kws={'alpha': 0.6},          # Transparency of the scatter points
    line_kws={'color': 'red'}            # Color of the regression line
)

# Add a title with the correlation coefficient and p-value
plt.title(f'Vegetarian Restaurant Density and Marriage Rate\nr = {r_value:.2f}, p = {p_value:.3f}')

# Label the axes
plt.xlabel('Vegetarian Restaurant Density ')
plt.ylabel('Marriage Rate ')

# Show the plot
plt.show()